import fs from 'node:fs';
import vm from 'node:vm';
const html=fs.readFileSync(new URL('../src/index.html',import.meta.url),'utf8');
const start=html.indexOf('  // NABA Cognitive Intelligence v1.6');
const end=html.indexOf('  // NABA Email Intelligence v1.5',start);
if(start<0||end<0) throw new Error('Cognitive block not found');
const mem={};
globalThis.localStorage={getItem:k=>Object.prototype.hasOwnProperty.call(mem,k)?mem[k]:null,setItem:(k,v)=>{mem[k]=String(v)}};
globalThis.window={NabaFleetAI:{}};
globalThis.normalizeArabicNameLite=s=>String(s||'').replace(/[أإآ]/g,'ا').replace(/ة/g,'ه').replace(/\s+/g,' ').trim().toLowerCase();
globalThis.nabaAiPlateKey=s=>normalizeArabicNameLite(s).replace(/\s+/g,'');
globalThis.APP={FLEET:[{plate:'ا ب ج 1234',driver:'محمد كمال',worksite:'مشروع أ',vehicle_state:'تعمل',insurance_status:'ساري',inspection_status:'ساري'}]};
globalThis.nabaAiVehicle360=()=>({ok:true,plate:'ا ب ج 1234',vehicle:APP.FLEET[0],dataConfidence:{score:90}});
globalThis.computeSystemAlerts=()=>[{plate:'ا ب ج 1234',severity:'high',title:'صيانة متأخرة'}];
globalThis.nabaAiAudit=()=>{};globalThis.registerNabaAiSkill=()=>{};globalThis.getNabaQuestionPlate=()=> 'ا ب ج 1234';
vm.runInThisContext(html.slice(start,end));
const assert=(c,m)=>{if(!c)throw new Error(m)};
const m=nabaAiRemember('episodic',{note:'محمد كمال طلب ديزل'},{source:'smoke',confidence:.9,entities:['محمد كمال']});
assert(nabaAiRecall('محمد كمال',{limit:5}).items.some(x=>x.id===m.id),'memory recall');
const ev=nabaAiAddEvidence({claim:'السائق المسجل محمد كمال',classification:'fact',source:'APP.FLEET',sourceId:'ا ب ج 1234',entities:['ا ب ج 1234'],confidence:.95});
assert(nabaAiAssessClaim('السائق محمد كمال',[ev.evidence.id]).status==='supported','evidence assessment');
const snap=nabaAiWorldSnapshot('ا ب ج 1234'); assert(snap.ok&&snap.state.riskHeuristic===25,'world snapshot');
const sim=nabaAiSimulateVehicle('ا ب ج 1234',['maintenance']); assert(sim.scenario.projectedRiskHeuristic===0&&sim.guard.requiresHumanApproval,'simulation guard');
nabaAiRemember('episodic',{fact:'معلومة قابلة للتثبيت'},{source:'smoke',durable:true,confidence:.8});
assert(nabaAiConsolidateMemory().promoted>=1,'consolidation');
assert(nabaAiRecall('معلومة قابلة للتثبيت',{limit:10}).items.some(x=>x.kind==='semantic'&&x.requiresHumanValidation),'semantic human-validation guard');
console.log('COGNITIVE_SMOKE_OK');
